version: '3'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario
      MONGO_INITDB_ROOT_PASSWORD: contraseña
      MONGO_INITDB_DATABASE: Entrada_de_ruedas